# Generated by Django 5.0.7 on 2024-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MutsaUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("nickname", models.CharField(max_length=1024, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("description", models.TextField(max_length=500)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("mbti", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
