# Generated by Django 5.0.7 on 2024-07-14 18:08

import auths.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="mutsauser",
            managers=[
                ("objects", auths.models.MutsaUserManager()),
            ],
        ),
    ]
