# Generated by Django 5.0.7 on 2024-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0002_alter_mutsauser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutsauser",
            name="login",
            field=models.BooleanField(default=True),
        ),
    ]
