# Generated by Django 5.0.7 on 2024-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0003_mutsauser_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mutsauser",
            name="age",
        ),
        migrations.RemoveField(
            model_name="mutsauser",
            name="description",
        ),
        migrations.RemoveField(
            model_name="mutsauser",
            name="mbti",
        ),
        migrations.AddField(
            model_name="mutsauser",
            name="school",
            field=models.CharField(default="-", max_length=1024),
        ),
    ]
